language: python

env:
  global:
    # Doctr deploy key for amurzeau/streamlink-docs
    - secure: "OSElq67DOEQ/oI7jgqhxFZhbmhGfmT3RSTQwlAz4MwGBzBznT6H5GFnne7O4XUiGrQu1hC6xLNtYkOzMwSauDqypZCbay7rF4x1yTtYbx0ev2MxKjpiMnphbnJJPMA3l1Der0+Er9zgN/BnVgVMe78P/VNUCdFKiDqPdnsCjtl9mBb/Nj/VpPrvk+1HXLG1ZasV7WVaTlHgQtpwjGiDdpsQNW8icYBbVitOMjtByDKvIVJwXpJorI/TNOW1kfMDldhca9MqLTPR88E+SgN3huoVym8nA8nzC0iBDyD5V1oGZ+sxFHn1nvawwYPr5CSGKk8Us2oktGGzDSsMYaPHHxbeVNikgs+Zn0AJfVq/XTEpKJ4yNMEvUZcF32OdSFb9Ap5AN65QKXV2GFWy23zmSwQdvuI6VfTaN1TscN0TXMvpO/sSEbr62wwT/ZuTGVMN3jhtcYyN5J6plt9zDcmGGHq9uQKNEcYTrLLFD1NVeE9zow1gdVJsWnp/KVsZwru8+ma+7jin0E730BSz++uxbbKOMqA/ZBQ7Z3mc+Z+zjQ8ITl84KXYXfuOQQMg/Jm6YgEXeiWkeIoNN5YFKdw5Lq/yq85ZdBUwFin8itC2PzDeutuj3SGPiv7v6p/OPdeKyO40mkKVo+ZYfDluYW5kK3AEyCMZcniZbmhgvsZee6VUU="

git:
  depth: 300

matrix:
  include:
  - python: '3.5'
    env: BUILD_DOCS=yes

before_install:
  - pip install --disable-pip-version-check --upgrade pip setuptools
  - pip install --upgrade -r dev-requirements.txt
  - pip install pycountry
  - if [[ $BUILD_DOCS == 'yes' ]]; then
      pip install -r docs-requirements.txt;
      pip install doctr;
    fi

install:
  - pip install -e .

script:
  - pytest --cov
  - flake8 --statistics --count
  - if [[ $BUILD_DOCS == 'yes' ]]; then make --directory=docs html; fi

after_success:
  - set -e
  # latest version - push docs for master
  - TRAVIS_REPO_SLUG="amurzeau/streamlink-debian" doctr deploy --deploy-repo amurzeau/streamlink-docs --no-require-master .

doctr:
  deploy-repo: amurzeau/streamlink-docs
  key-path: github_deploy_key_amurzeau_streamlink_docs.enc
